# Generated by Django 5.0.1 on 2024-02-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
