# Generated by Django 5.0.1 on 2024-02-23 19:31

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lose_user', models.ManyToManyField(related_name='lose_matches', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('win_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='win_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMatchRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('win_count', models.PositiveIntegerField(default=0)),
                ('lose_count', models.PositiveIntegerField(default=0)),
                ('match_count', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('win_count'), '+', models.F('lose_count')), output_field=models.PositiveIntegerField(default=0))),
                ('win_rate', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('win_count'), '/', django.db.models.expressions.CombinedExpression(models.F('win_count'), '+', models.F('lose_count'))), '*', models.Value(100)), output_field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='match_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
