# Generated by Django 5.0.1 on 2024-02-18 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('win_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='win_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
